#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./lib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib.sh"

# Set Shellib version
function build {
    local build_dir="build"
    local src_dir="src"

    rm -rf "$build_dir"
    mkdir "$build_dir"
    cp "$src_dir/shellib.sh" "$build_dir/shellib.sh"
}

# Skip functions execution under test
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    build
fi
