#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./lib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib.sh"

# Set Shellib version
function build {
    local build_dir='build'

    rm -rf "$build_dir"
    mkdir "$build_dir"
    cp 'shellib.sh' "$build_dir/shellib.sh"

    # shellcheck disable=SC2016
    sed 's/\.\s"$shellib_path\/src\/globals.sh"/\n# . src\/globals.sh/g' -i "$build_dir/shellib.sh"
    cat src/globals.sh >>"$build_dir/shellib.sh"
}

# Skip functions execution under test
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    build
fi
