#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=../shellib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../shellib.sh"

# Set Shellib version
function build {
    local build_dir='build'
    local source_files
    local source_file
    local target_file="$build_dir/shellib.sh"

    rm -rf "$build_dir"
    mkdir "$build_dir"
    cp 'shellib.sh' "$target_file"

    source_files=$(grep -oP "(?<=^\\.\\s\"[$]shellib_path/)[^\"]*(?=\")" "$target_file")
    for source_file in $source_files; do
        sed "s~\\.\\s\"\$shellib_path/$source_file\"~#. $source_file~g" -i "$target_file"
        cat "$source_file" >>"$target_file"
    done
}

# Skip functions execution under test
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    build
fi
