#!/usr/bin/env bash
#set -e
#set -o pipefail
#set -u

LANG=C

# Pack
if [ -z "$1" ]; then
    echo "Next version expected as a first parameter" >&2
    exit 1
else
    # Set package metadata
    CURRENT_DIR=${PWD##*/}
    PACKAGE_NAME="${CI_PROJECT_NAME:-$CURRENT_DIR}"
    PACKAGE_VERSION_FULL="$1"
    PACKAGE_ARCH="all"
    PACKAGE_FILE="${PACKAGE_NAME}_${PACKAGE_VERSION_FULL}_$PACKAGE_ARCH"
    PACKAGE_SECTION="libs"
    PACKAGE_HOMEPAGE="${CI_PROJECT_URL:-}"
    if [ -n "$GITLAB_USER_NAME" ]; then
        PACKAGE_MAINTAINER="$GITLAB_USER_NAME"
        if [ -n "$GITLAB_USER_EMAIL" ]; then
            PACKAGE_MAINTAINER="$PACKAGE_MAINTAINER <$GITLAB_USER_EMAIL>"
        fi
    else
        USER_NAME_FULL="$(getent passwd "$USER" | cut -d ':' -f 5 | cut -d ',' -f 1)"
        PACKAGE_MAINTAINER="$USER_NAME_FULL"
    fi
    PACKAGE_DESCRIPTION="${CI_PROJECT_TITLE:-$CURRENT_DIR}
 Simple Bash scripting library."

    # Prepare package
    BUILD_DIR="build"
    PACKAGE_ROOT="$BUILD_DIR/$PACKAGE_FILE"
    PACKAGE_DEBIAN_DIR="$PACKAGE_ROOT/DEBIAN"
    PACKAGE_CONTROL_FILE_PATH="$PACKAGE_DEBIAN_DIR/control"

    if [ -n "$2" ]; then
        echo "Package metadata:"
        echo "- Package name: $PACKAGE_NAME"
        echo "- Package version: $PACKAGE_VERSION_FULL"
        echo "- Package architecture: $PACKAGE_ARCH"
        echo "- Package file: $PACKAGE_FILE"
        echo "- Package section: $PACKAGE_SECTION"
        echo "- Package homepage: $PACKAGE_HOMEPAGE"
        echo "- Package maintainer: $PACKAGE_MAINTAINER"
        echo "- Package description: $PACKAGE_DESCRIPTION"
        echo "Package:"
        echo "- Build directory: $BUILD_DIR"
        echo "- Package root: $PACKAGE_ROOT"
        echo "- Package control file path: $PACKAGE_CONTROL_FILE_PATH"
        exit 0
    else
        if [ ! -f "$BUILD_DIR/shellib.sh" ]; then
            echo "$BUILD_DIR/shellib.sh does not exist, nothing to pack" >&2
            exit 1
        else
            # Prepare package contents
            mkdir -p "$PACKAGE_DEBIAN_DIR"
            PACKAGE_LIB_DIR="$PACKAGE_ROOT/usr/lib"
            mkdir -p "$PACKAGE_LIB_DIR"
            mv "$BUILD_DIR/shellib.sh" "$PACKAGE_LIB_DIR/shellib.sh"

            # Prepare package metadata
            touch "$PACKAGE_CONTROL_FILE_PATH"
            {
                echo "Package: $PACKAGE_NAME"
                echo "Version: $PACKAGE_VERSION_FULL"
                echo "Architecture: $PACKAGE_ARCH"
                echo "Section: $PACKAGE_SECTION"
                echo "Homepage: $PACKAGE_HOMEPAGE"
                echo "Maintainer: $PACKAGE_MAINTAINER"
                echo "Description: $PACKAGE_DESCRIPTION"
            } >"$PACKAGE_CONTROL_FILE_PATH"

            # Create package
            (
                cd "$BUILD_DIR" || exit 1
                dpkg-deb --build --root-owner-group "$PACKAGE_FILE"
            )
            exit 0

            # Clean up
            rm -rf "$PACKAGE_ROOT"
        fi
    fi
fi
